web:
  build: .
  volumes:
    - .:/app
  volumes_from:
    - gems
  ports:
    - "3000:3000"
  links:
    - db
    - redis

db:
  image: postgres
  ports:
    - "5432:5432"

redis:
  image: redis

gems:
  image: busybox
  volumes:
    - /gems
